language: python

python:
  - "2.7"
  - "3.4"

# command to install dependencies
install: 
  - "pip install ."
  - "cat requirements.txt | xargs pip install"

# command to run tests
script: nosetests
